# See Dockerfile for the full build instructions
sudo: required
language: python
cache: pip
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:

    - stage: SimTests
      python: 3.7
      os: windows
      language: shell
      before_install:
        - powershell "Invoke-WebRequest -outfile miniconda3.exe https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe"
        - powershell "Start-Process .\miniconda3.exe -ArgumentList '/S /D=C:\miniconda3' -Wait"
        - powershell "\$env:Path = ';C:\miniconda3;C:\miniconda3\Library\mingw-w64\bin;C:\miniconda3\Library\usr\bin;C:\miniconda3\Library\bin;C:\miniconda3\Scripts;C:\miniconda3\bin;C:\miniconda3\condabin' + \$env:Path ; conda install --yes -c msys2 m2-base m2-make m2w64-toolchain libpython"
       
        - powershell "Invoke-WebRequest -Uri http://bleyer.org/icarus/iverilog-10.1.1-x64_setup.exe -OutFile iverilog-10.1.1-x64_setup.exe"
        - powershell "Start-Process .\iverilog-10.1.1-x64_setup -ArgumentList '/VERYSILENT' -Wait"
      script:
        - powershell "\$env:Path = ';C:\miniconda3;C:\miniconda3\Library\mingw-w64\bin;C:\miniconda3\Library\usr\bin;C:\miniconda3\Library\bin;C:\miniconda3\Scripts;C:\miniconda3\bin;C:\miniconda3\condabin' + \$env:Path + ';C:\iverilog\bin' ; python setup.py install ; make test"
