# See Dockerfile for the full build instructions
sudo: required
language: python
cache: pip
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
    
    #- stage: SimTests
    #  python: 3.7
    #  os: windows
    #  language: shell
    #  before_install:
    #    - docker build -f Dockerfile.windows .
    #  script:
    #    - docker exec -it -e TRAVIS=true cocotb pip install tox; cd /src; tox -e py37

    - stage: SimTests
      python: 3.7
      os: windows
      language: shell
      before_install:
        - PowerShell Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
        - PowerShell "& "".\install.ps1"""
        - PowerShell Write-Output $env:Path
        
      script:
        - PowerShell -Command "echo $env:Path"
        - PowerShell -Command "tox -e py37"
        
