# See Dockerfile for the full build instructions
sudo: required
language: python
cache: pip
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
    
    #- stage: SimTests
    #  python: 3.7
    #  os: windows
    #  language: shell
    #  before_install:
    #    - docker build -f Dockerfile.windows .
    #  script:
    #    - docker exec -it -e TRAVIS=true cocotb pip install tox; cd /src; tox -e py37

    - stage: SimTests
      python: 3.7
      os: windows
      language: shell
      before_install:
        - docker build -t cocotb -f Dockerfile.windows .
        - docker images -a
        - docker run -it --name cocotb cocotb python setup.py install; make test 
        - docker ps -a
      script:
        - docker exec -it cocotb python setup.py install; make test 
