# See Dockerfile for the full build instructions
sudo: required
language: python
dist: xenial
cache:
  directories:
  - iverilog

git:
  quiet: true

services:
  - docker

jobs:
  include:

    - stage: SimTests
      python: 3.7
      os: windows
      language: shell
      before_install:
        - docker build -t cocotb -f Dockerfile.windows .
      script:
        - docker run cocotb powershell 'python setup.py install ; make test'

    - stage: SimTests
      os: osx
      osx_image: xcode11.2
      language: shell
      python: 3.7
      before_install: &osx_prep
        - brew update-reset
        - brew install icarus-verilog
        - pip3 install tox
      script:
        - pip3 install -v -e .
        - python cocotb/build_libs.py 
        - PYTHON_BIN=python3 make
        #- tox -e py37



