# See Dockerfile for the full build instructions
sudo: required
language: python
cache: pip
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
    - stage: SimTests
      python: 3.7
      before_install: &travis_linx_prep
        - sudo apt-get install gperf
        - git clone https://github.com/steveicarus/iverilog.git --depth=1 --branch v10_2
        - cd iverilog && autoconf && ./configure && make -j2 && sudo make install && cd ..
        - pip install tox
        - pyenv global system $TRAVIS_PYTHON_VERSION
      script:
        - tox -e py37
        
    - stage: SimTests
      python: 3.7
      os: windows
      language: shell
      before_install:
        - docker build -f Dockerfile.windows .
      script:
        - docker exec -it -e TRAVIS=true cocotb pip install tox; cd /src; tox -e py37
