# See Dockerfile for the full build instructions
sudo: required
language: python
cache: pip
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
    - stage: SimTests
      python: 3.7
      before_install: &travis_linx_prep
        - sudo apt-get install gperf
        - git clone https://github.com/steveicarus/iverilog.git --depth=1 --branch v10_2
        - cd iverilog && autoconf && ./configure && make -j2 && sudo make install && cd ..
        - pip install tox
        - pyenv global system $TRAVIS_PYTHON_VERSION
      script:
        - tox -e py37
        
    #- stage: SimTests
    #  python: 3.7
    #  os: windows
    #  language: shell
    #  before_install:
    #    - docker build -f Dockerfile.windows .
    #  script:
    #    - docker exec -it -e TRAVIS=true cocotb pip install tox; cd /src; tox -e py37

    - stage: SimTests
      python: 3.7
      os: windows
      language: shell
      before_install:
        - PowerShell -Command Invoke-WebRequest -Uri http://bleyer.org/icarus/iverilog-10.1.1-x64_setup.exe -OutFile iverilog-10.1.1-x64_setup.exe
        - PowerShell -Command "Start-Process .\iverilog-10.1.1-x64_setup -ArgumentList '/VERYSILENT'
        - setx path "%path%;C:\iverilog\bin"
        - iverilog
        
        - PowerShell -Command "Invoke-WebRequest -outfile miniconda3.exe https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe"
        - miniconda3.exe /S /D=C:\miniconda3
        - setx path "C:\miniconda3;C:\miniconda3\bin;C:\miniconda3\Scripts;%path%"
        - conda install --yes -c msys2 m2-base m2-make m2w64-toolchain
        - conda install --yes libpython
        - pip install coverage xunitparser

      script:
        - tox -e py37
        
