# See Dockerfile for the full build instructions
sudo: required
language: python
cache: pip
dist: xenial

git:
  quiet: true

services:
  - docker

jobs:
  include:
    - stage: SimTests
      os: linux
      language: generic
      python: 2.7
      env: SIM=ghdl
      before_install:
        - sudo apt-get install gnat
        - git clone https://github.com/ghdl/ghdl.git --depth=1 --branch v0.36
        - cd ghdl && ./configure && make -j2 && sudo make install && cd ..
        - pip install tox
        - pyenv global system $TRAVIS_PYTHON_VERSION
      script:
        - tox -e py37
