# See Dockerfile for the full build instructions
sudo: required
language: cpp

os:
#  - linux
  - windows
  
services:
  - docker

script:
  #- set
  #- gcc -v
  - PowerShell -Command Invoke-WebRequest -Uri http://bleyer.org/icarus/iverilog-10.1.1-x64_setup.exe -OutFile iverilog-10.1.1-x64_setup.exe
  - dir
  - cmd /K iverilog-10.1.1-x64_setup.exe /SILENT
  - dir c:

