sudo: required
cache: pip

git:
  quiet: true

jobs:
  include:
    - stage: PythonLint
      os: linux
      language: python
      python: 3.5
      install: pip install flake8
      script: flake8 --exit-zero cocotb/
      
    - stage: SimTests
      os: linux
      language: python
      python: 2.7
      before_install: &linux_prep
        - sudo apt-get install gperf
        - git clone https://github.com/steveicarus/iverilog.git --depth=1 --branch v10_2
        - cd iverilog && autoconf && ./configure && make -j2 && sudo make install && cd ..
        - pip install tox
      script:
        - tox -e py27

    - stage: SimTests
      os: linux
      language: python
      python: 3.5
      before_install: *linux_prep 
      script:
        - tox -e py35
        
    - stage: SimTests
      os: osx
      language: generic
      python: 2.7
      before_install: &osx_prep
        - brew install icarus-verilog
        - pip install tox
      script:
        - tox -e py27

    - stage: SimTests
      os: osx
      language: generic
      python: 3.6
      before_install: *osx_prep
      script:
        - tox -e py36
